import express from 'express';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { listSites, queryPerformance, resolveSite, serviceAccountIdentity, mergePeriodRows, rollingRanges } from './gsc.mjs';
import { allowedEmail, oauthMetadata, parseScope, pkceChallenge, protectedResourceMetadata, publicBaseUrl, resourceUrl, scopeAllowed, signToken, verifyToken } from './oauth.mjs';

const app=express(); app.set('trust proxy',true); app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:false}));
const ro={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:true};
const dims=z.array(z.enum(['query','page','country','device','date','searchAppearance'])).min(1).max(3);
const result=d=>({content:[{type:'text',text:JSON.stringify(d)}],structuredContent:d});

function buildServer(){
 const s=new McpServer({name:'GSC OpenSEO',version:'1.0.0'});
 s.registerTool('whoami',{description:'Return authenticated user and configured GSC project.',inputSchema:{},annotations:ro},async(_a,e)=>result({authenticated_user:e?.authInfo?.extra?.email||null,service_account:serviceAccountIdentity().client_email,project_id:process.env.PROJECT_ID||'sklepzherbatami-pl',domain:process.env.PROJECT_DOMAIN||'sklepzherbatami.pl',access:'read-only'}));
 s.registerTool('list_projects',{description:'List SEO projects exposed by this MCP.',inputSchema:{},annotations:ro},async()=>result({projects:[{id:process.env.PROJECT_ID||'sklepzherbatami-pl',domain:process.env.PROJECT_DOMAIN||'sklepzherbatami.pl',country:'PL',language:'pl',default_search_console_property:process.env.DEFAULT_GSC_SITE||null}]}));
 s.registerTool('list_search_console_properties',{description:'List allowed GSC properties.',inputSchema:{},annotations:ro},async()=>{const d=await listSites();const a=new Set((process.env.ALLOWED_GSC_SITES||'').split(',').map(x=>x.trim()).filter(Boolean));return result({sites:(d.siteEntry||[]).filter(x=>!a.size||a.has(x.siteUrl))});});
 s.registerTool('get_search_console_performance',{description:'Read GSC clicks, impressions, CTR and average position.',inputSchema:{siteUrl:z.string().optional(),startDate:z.string(),endDate:z.string(),dimensions:dims.default(['page']),pageContains:z.string().optional(),queryContains:z.string().optional(),rowLimit:z.number().int().min(1).max(25000).default(1000)},annotations:ro},async x=>{const site=resolveSite(x.siteUrl),filters=[];if(x.pageContains)filters.push({dimension:'page',operator:'contains',expression:x.pageContains});if(x.queryContains)filters.push({dimension:'query',operator:'contains',expression:x.queryContains});const body={startDate:x.startDate,endDate:x.endDate,dimensions:x.dimensions,type:'web',rowLimit:x.rowLimit};if(filters.length)body.dimensionFilterGroups=[{groupType:'and',filters}];const d=await queryPerformance(site,body);return result({siteUrl:site,startDate:x.startDate,endDate:x.endDate,dimensions:x.dimensions,rows:d.rows||[]});});
 s.registerTool('get_collection_opportunities',{description:'Find Shopify collection pages with GSC visibility and positions 4-20 by default, comparing equal periods.',inputSchema:{siteUrl:z.string().optional(),days:z.number().int().min(14).max(180).default(90),gscLagDays:z.number().int().min(1).max(7).default(3),minImpressions:z.number().int().min(0).default(100),minPosition:z.number().min(1).max(100).default(4),maxPosition:z.number().min(1).max(100).default(20),limit:z.number().int().min(1).max(200).default(50)},annotations:ro},async x=>{const site=resolveSite(x.siteUrl),r=rollingRanges(x.days,x.gscLagDays);const body=(p)=>({startDate:p.startDate,endDate:p.endDate,dimensions:['page'],type:'web',rowLimit:25000,dimensionFilterGroups:[{groupType:'and',filters:[{dimension:'page',operator:'contains',expression:'/collections/'}]}]});const [c,p]=await Promise.all([queryPerformance(site,body(r.current)),queryPerformance(site,body(r.previous))]);const rows=mergePeriodRows(c.rows||[],p.rows||[]).filter(v=>v.current.impressions>=x.minImpressions&&v.current.position>=x.minPosition&&v.current.position<=x.maxPosition).sort((a,b)=>b.current.impressions-a.current.impressions).slice(0,x.limit);return result({siteUrl:site,current_period:r.current,previous_period:r.previous,rows});});
 return s;
}

const err=(res,status,error,desc)=>res.status(status).json({error,error_description:desc});
app.get('/',(_q,res)=>res.json({name:'GSC OpenSEO MCP',status:'ok',mcp:resourceUrl()})); app.get('/health',(_q,res)=>res.json({ok:true}));
app.get('/.well-known/oauth-authorization-server',(_q,res)=>res.json(oauthMetadata())); app.get('/.well-known/oauth-protected-resource',(_q,res)=>res.json(protectedResourceMetadata())); app.get('/.well-known/oauth-protected-resource/mcp',(_q,res)=>res.json(protectedResourceMetadata()));
app.post('/register',(req,res)=>{try{const uris=req.body?.redirect_uris;if(!Array.isArray(uris)||!uris.length)return err(res,400,'invalid_client_metadata','redirect_uris required');for(const u of uris)if(new URL(u).protocol!=='https:')return err(res,400,'invalid_redirect_uri','HTTPS only');const id=signToken({redirect_uris:uris,client_name:req.body?.client_name||'ChatGPT'},31536000,'client');res.status(201).json({...req.body,client_id:id,client_id_issued_at:Math.floor(Date.now()/1000),token_endpoint_auth_method:'none'});}catch(e){err(res,400,'invalid_client_metadata',e.message)}});
app.get('/authorize',(req,res)=>{try{const q=req.query,c=verifyToken(q.client_id,'client');if(q.response_type!=='code'||!c.redirect_uris?.includes(q.redirect_uri)||q.code_challenge_method!=='S256'||!q.code_challenge)return err(res,400,'invalid_request','Invalid OAuth request');if(!scopeAllowed(q.scope))return err(res,400,'invalid_scope','gsc:read required');if(!process.env.GOOGLE_OAUTH_CLIENT_ID||!process.env.GOOGLE_OAUTH_CLIENT_SECRET)return err(res,503,'temporarily_unavailable','Google OAuth not configured');const st=signToken({client_id:q.client_id,redirect_uri:q.redirect_uri,state:q.state||null,scope:String(q.scope),resource:resourceUrl(),code_challenge:q.code_challenge},600,'auth_state');const g=new URL('https://accounts.google.com/o/oauth2/v2/auth');g.search=new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,redirect_uri:`${publicBaseUrl()}/oauth/google/callback`,response_type:'code',scope:'openid email profile',state:st,prompt:'select_account'});res.setHeader('Set-Cookie',`__Host-gsc_mcp_state=${encodeURIComponent(st)}; HttpOnly; Secure; Path=/; SameSite=Lax; Max-Age=600`);res.redirect(g.toString());}catch(e){err(res,400,'invalid_request',e.message)}});
app.get('/oauth/google/callback',async(req,res)=>{try{const c=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('__Host-gsc_mcp_state='));if(!c||decodeURIComponent(c.split('=')[1])!==req.query.state)return res.status(400).send('OAuth state mismatch');const st=verifyToken(req.query.state,'auth_state');const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,code:String(req.query.code),grant_type:'authorization_code',redirect_uri:`${publicBaseUrl()}/oauth/google/callback`})});const t=await tr.json();if(!tr.ok)throw new Error(JSON.stringify(t));const ur=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:`Bearer ${t.access_token}`}}),u=await ur.json();if(!u.verified_email||!allowedEmail(u.email))return res.status(403).send('Google account not allowed');const code=signToken({client_id:st.client_id,redirect_uri:st.redirect_uri,scope:st.scope,resource:st.resource,code_challenge:st.code_challenge,sub:u.id,email:u.email,name:u.name||null},300,'authorization_code');const r=new URL(st.redirect_uri);r.searchParams.set('code',code);if(st.state)r.searchParams.set('state',st.state);r.searchParams.set('iss',publicBaseUrl());res.redirect(r.toString());}catch(e){res.status(400).send(`Authorization failed: ${e.message}`)}});
app.post('/token',(req,res)=>{try{if(req.body?.grant_type==='authorization_code'){const c=verifyToken(req.body.code,'authorization_code');if(c.client_id!==req.body.client_id||c.redirect_uri!==req.body.redirect_uri||!req.body.code_verifier||pkceChallenge(req.body.code_verifier)!==c.code_challenge)return err(res,400,'invalid_grant','Grant validation failed');const scope=parseScope(c.scope).join(' '),base={iss:publicBaseUrl(),sub:c.sub,email:c.email,name:c.name,client_id:c.client_id,scope,aud:c.resource};return res.json({access_token:signToken(base,3600,'access'),token_type:'Bearer',expires_in:3600,refresh_token:signToken(base,7776000,'refresh'),scope});}if(req.body?.grant_type==='refresh_token'){const r=verifyToken(req.body.refresh_token,'refresh');if(r.client_id!==req.body.client_id)return err(res,400,'invalid_grant','client mismatch');return res.json({access_token:signToken({iss:publicBaseUrl(),sub:r.sub,email:r.email,name:r.name,client_id:r.client_id,scope:r.scope,aud:r.aud},3600,'access'),token_type:'Bearer',expires_in:3600,refresh_token:req.body.refresh_token,scope:r.scope});}err(res,400,'unsupported_grant_type','Unsupported grant');}catch(e){err(res,400,'invalid_grant',e.messae)}});
function auth(req,res,next){try{const m=(req.get('authorization')||'').match(/^Bearer\s+(.+)$/i);if(!m)throw new Error('Bearer token required');const t=verifyToken(m[1],'access');if(t.iss!==publicBaseUrl()||t.aud!==resourceUrl()||!parseScope(t.scope).includes('gsc:read'))throw new Error('Invalid token');req.auth={token:m[1],clientId:t.client_id,scopes:parseScope(t.scope),expiresAt:t.exp,extra:{email:t.email,name:t.name}};next();}catch(e){res.set('WWW-Authenticate', `Bearer resource_metadata="${publicBaseUrl()}/.well-known/oauth-protected-resource/mcp", scope="gsc:read"`);err(res,401,'invalid_token',e.message)}}
app.post('/mcp',auth,async(req,res)=>{const s=buildServer(),tr=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});try{await s.connect(tr);await tr.handleRequest(req,res,req.body);}catch(e){if(!res.headersSent)err(res,500,'mcp_error',e.message)}finally{try{await tr.close()}catch{}try{await s.close()}catch{}}});
const port=Number(process.env.PORT||3000);app.listen(port,'0.0.0.0',()=>console.log(`GSC OpenSEO MCP on ${publicBaseUrl()}`));
